version: "3.9"
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    network_mode: host
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influxdb:
    image: influxdb:2.2.0
    container_name: influxdb
    restart: always
    expose:
      - 8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
    network_mode: host

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
    network_mode: host

volumes:
  influxdb_data: {}
  grafana_data: {}

